### ISSUE TITLE
Global aliases get duplicated.

### ISSUE THREAD

**Issue by maciekr1234** [GameMakerDiscord/GMEdit#14] opened 2018-03-09 17:53 UTC
All of the global import aliases gets duplicated on autocomplete popout.

Edit: After some tests, they get duplicated only on the script which has #import "global" in it. It seems to be fine on the other scopes.

**Comment by YellowAfterlife** [comment] 2018-05-14 19:48
See if it's fixed in the new version.

**Comment by maciekr1234** [comment] 2018-05-21 11:43
No, the bug still persists in the newest version.

**Comment by YellowAfterlife** [comment] 2018-05-21 13:08
In that case I could use a snippet of code that reproduces the issue because doing `#import "global"` in a script does not produce duplicate results for me upon reloading.

**Comment by maciekr1234** [comment] 2018-05-21 13:27
I just realized that it just duplicates extension functions and macros, it doesn't duplicate scripts or project macros. Probably that's the reason why you couldn't reproduce this bug. :)

**Comment by YellowAfterlife** [comment] 2018-05-21 17:21
I'm still having issues with replicating this to be honest,
![image](https://user-images.githubusercontent.com/731492/40320443-751bf724-5d34-11e8-87a3-aa48046cd455.png)
(where magic_1 is an extension script renamed to `mg1` in import-global)

If you can make a small sample project, that'd be ideal.

**Closed** 2018-05-24 21:09 UTC
Labels: bug
